### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by AriGlockner** [username2112/Space-Project#53] opened 2019-12-05 22:35 UTC
1. Hallock Face Boss
2. Add more bosses after level 3
3. Instead of adding more aliens, make the aliens faster after a certain point.

**Comment by MohammedMohiuddin1** [comment] 2019-12-06 16:44
So i dont think its possible to do a Hallock Face Boss because of copyright issues, we will be adding more bosses after level 3, the aliens becoming faster is already something we will add back into the game, but the issue is if we add fewer but faster aliens the game gets pretty easy and we want to make it as challenging as possible, so that's why we have a larger number of aliens, (although we are adding new types of shots that can kill  more aliens but im pretty sure thats for next week).

**Comment by username2112** [comment] 2019-12-19 04:07
we will consider the idea of making the aliens faster however, it does potentially present the issue of the aliens out speeding the player, as such that likely won't be implemented until we add a way for the player to speed up, such as power-ups. However your second suggestion has been implemented in this weeks update.

**Closed as completed by username2112** 2019-12-19 04:07 UTC
